### ISSUE TITLE
Multiple indexes

### ISSUE THREAD

**Issue by mihailtd** [simonguest/swagger-mongoose#52]
Hello,
Is it possible to have multiple indexes on a schema? If so, how?
I tried:

```
definitions:
  House:
    x-swagger-mongoose:
      index:
		index_1:
			lng: 1
			lat: 1
		index_2:
			someProp: 1
			unique: true
```
and it does not work.

Thanks!
