### ISSUE TITLE
Support number with format

### ISSUE THREAD

**Issue by scaleupcto** [simonguest/swagger-mongoose#7]
As I understand it, swagger 2.0 requires numbers to be declared in this way:

``` yaml
      my_num_field:
        type: number
        format: float
```

But this throws `Error: Unrecognized schema type: number` with this library. 

Instead add `case 'number'` to the switch statement here: https://github.com/simonguest/swagger-mongoose/blob/master/lib/index.js#L8
